name: 'Configure CLOUD ENV'
description: 'Configure Cloud ENV, AWS, Aliyun, etc.'
author: 'tianweiding'
branding: 
  icon: cloud
  color: yellow
inputs:
  profile:
    required: true
    description: 'Profile name: default/aws-us/aws-cn/aliyun/aliyun-prod'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'
